### ISSUE TITLE
Add a note on the labs

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/javascript-arithmetic-lab#1]
Can we talk a bit more about this lab at the end? 

We don't have to tell them how to do it, but just some more explanation such as you're going to write "three (not sure how many offhand) functions." Use the tests to figure out how to do it. 

Also in the index.js file can we just write the list of the functions and then comment in where they should write their code? 

@jmburges

**Comment by pletcher** [comment]
I'm totally down with giving them a bit more help about how many functions they need to write (it'll make the weaning process slower for these labs, which is probably good).

I'd rather not write in the functions for now, if that's okay. It's sort of a goal (which we can talk about) of mine to try to move away from doing that in labs, and instead to guide students about naming from the test descriptions (which this lab does) -- that is, if the tests require specific names.

Can we try that for now?

**Comment by AnnJohn** [comment]
sure im willing to try that. just giving them the number of functions that they have to write would be good. Maybe also telling them explicitly that they should use the test output to figure out the name of their functions would be helpful.

**Comment by pletcher** [comment]
It does include the names in the README :)
