### ISSUE TITLE
Possible error in the lesson

### ISSUE THREAD

**Issue by yaboisharf** [learn-co-curriculum/javascript-arithmetic-lab#10]
I ran a learn test on the terminal which reported that the test failed, however the test passed on the website's lesson. I'm not sure whats goign on
![rpotp `1](https://cloud.githubusercontent.com/assets/22223958/18868111/03db562a-8475-11e6-9b3b-019090954f37.png)

This is the code I used to get this error.
`function add(a,b)
{
  return a + b;
}

function subtract(a,b)
{
  return a - b;
}

function multiply(a,b)
{
  return a \* b;
}

funtion divide(a,b)
{
  return a / b;
}
`

**Comment by AnnJohn** [comment]
hi @yaboisharf123 could you please use Ask a Question and someone from our team will help you out with the problem. If it is an issue with the lab, then they'll raise an issue on it afterwards. Thanks!
