### ISSUE TITLE
Can't figure out hoisting

### ISSUE THREAD

**Issue by masaleen** [learn-co-curriculum/javascript-arithmetic-lab#15]
I've tried everything and can't seem to get how to fix this code:

function crazy() {
  // fix the code in here:
 thisIsCrazy();
  var thisIsCrazy = function(){
    console.log("hey!!!")
  }
}
I am ONLY supposed to add/edit underneath the comment, correct?

**Comment by masaleen** [comment]
Tried:

function crazy() {
    var crazy = function thisIsCrazy(){
      console.log("hey!!!")
  }
}

**Comment by JessRudder** [comment]
Hi @masaleen if you're still having trouble, please use the "Ask a Question" feature in Learn to get live help from a Learn Expert.
