### ISSUE TITLE
Fix the Scope Lab

### ISSUE THREAD

**Issue by rhogotargaryen** [learn-co-curriculum/javascript-arithmetic-lab#21]
Hey big thanks in advanced,

I am stuck on the Fix the Scope Lab on the last test.  The last lines of my code are as follows:

var theFunk = funkyFunction();
theFunk();

ive tried a lot of other methods but this is my best guess atm.  Banging my head against the wall and my tremendous magical abilities have no effect. please help!

-D

**Comment by asabogal** [comment]
wrong lab

**Comment by maxwellbenton** [comment]
Hi @rhogotargaryen,

Sorry to hear you were having trouble with the Fix the Scope lab. We recently updated the lab to include additional instructions and expanded the provided hint to help prevent students from encountering the same problem.

Thank you for taking the time to provide feedback!
