### ISSUE TITLE
The IDE Lesson Broke

### ISSUE THREAD

**Issue by shoaryon** [learn-co-curriculum/javascript-arithmetic-lab#26]
When I click on "Open IDE" it tells me that it can't find the lesson and to check my input.

**Comment by maxwellbenton** [comment]
Hi @shoaryon,

Sorry to hear you were having difficulty with this lab. We've updated the contents of this lesson recently and confirmed that it is successfully working now and will clone down as intended.

We apologize for any frustration this may have caused, but we appreciate you taking the time to let us know about your experience!
