### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by mprizzuto** [learn-co-curriculum/javascript-arithmetic-lab#34]
i tried to click http://jsforallof.us/2014/07/10/pre-increment-vs-post-increment/ and first i got sent to https://get1.mysecurify.com/view/item_6760.html (dont click, spamware) and then i got sent to a disambiguation page. looks like this website doesnt exist anymore.

please remove

**Comment by maxwellbenton** [comment]
Hi @mprizzuto, 

Thank you for spotting this and providing feedback. We've updated this link so that it correctly points to the MDN documentation on incrementing in JavaScript, which should resolve this issue.
