### ISSUE TITLE
Pre increment and post increment info link does not work

### ISSUE THREAD

**Issue by andreip1** [learn-co-curriculum/javascript-arithmetic-lab#35]
There's a paragraph "If you're interested in the difference, take a look _**here**_" Where _**here**_ is a link that doesn't work.

**Comment by maxwellbenton** [comment]
Hi @Swishyfishie,

Thank you for spotting this and providing feedback. We've updated this link so that it correctly points to the MDN documentation on incrementing in JavaScript, which should resolve this issue.
