### ISSUE TITLE
Clicking "here" doesn't direct to the proper site

### ISSUE THREAD

**Issue by austinoso** [learn-co-curriculum/javascript-arithmetic-lab#37]
> "But generally, you will see them placed after the number (and we recommend that that's where you put them). If you're interested in the difference, take a look [here](http://jsforallof.us/2014/07/10/pre-increment-vs-post-increment/)"

I tried clicking "here" but instead of reaching `http://jsforallof.us/2014/07/10/pre-increment-vs-post-increment` I was redirected to `http://ww12.jsforallof.us/`

**Comment by maxwellbenton** [comment]
Hi @austinoso,

Thank you for spotting this and providing feedback. We've updated this link so that it correctly points to the MDN documentation on incrementing in JavaScript, which should resolve this issue.
