### ISSUE TITLE
Link no longer works

### ISSUE THREAD

**Issue by HuDaMan0621** [learn-co-curriculum/javascript-arithmetic-lab#39]
But generally, you will see them placed after the number (and we recommend that that's where you put them). If you're interested in the difference, take a look here (http://jsforallof.us/2014/07/10/pre-increment-vs-post-increment/)

**Comment by maxwellbenton** [comment]
Hi @HuDaMan0621, 

Thank you for spotting this and providing feedback. We've updated this link so that it correctly points to the MDN documentation on incrementing in JavaScript, which should resolve this issue.
