### ISSUE TITLE
Typos in parseFloat() function statement

### ISSUE THREAD

**Issue by tyunist** [learn-co-curriculum/javascript-arithmetic-lab#7]
Hi, in Introduction to Javascript/ Javascript Arithmetic Lab, there seems to have a **TYPO**. 
It says that: **"Unlike parseInt(), parseFloat() accepts only a single argument, the thing to be parsed."** 
But when i tried parseFloat('2.2.0000000000000000001',10), it returned: 2.2. 
Beside, parseFloat() can accept 1 argument two. So I think this function accepts both.

**Comment by AnnJohn** [comment]
hi @tyunist the function can accept both arguments but it will still only operate on the first argument. thanks
